# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TokyoInterfaz.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 753)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Destino = QtWidgets.QPushButton(self.centralwidget)
        self.Destino.setGeometry(QtCore.QRect(0, 130, 91, 41))
        self.Destino.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Destino.setObjectName("Destino")
        self.Origen = QtWidgets.QPushButton(self.centralwidget)
        self.Origen.setGeometry(QtCore.QRect(0, 90, 91, 41))
        self.Origen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Origen.setObjectName("Origen")
        self.comboOrigen = QtWidgets.QComboBox(self.centralwidget)
        self.comboOrigen.setGeometry(QtCore.QRect(90, 90, 171, 41))
        self.comboOrigen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboOrigen.setObjectName("comboOrigen")
        self.comboOrigen.addItem("")
        self.comboOrigen.setItemText(0, "")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.comboOrigen.addItem("")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(-40, 0, 801, 81))
        self.Titulo.setStyleSheet("background-color: rgb(82, 73, 204);")
        self.Titulo.setObjectName("Titulo")
        self.MapaMetro = QtWidgets.QLabel(self.centralwidget)
        self.MapaMetro.setGeometry(QtCore.QRect(0, 0, 1241, 841))
        self.MapaMetro.setMaximumSize(QtCore.QSize(1241, 841))
        self.MapaMetro.setText("")
        self.MapaMetro.setPixmap(QtGui.QPixmap("PycharmProjects/IA/Tokyo.jpg"))
        self.MapaMetro.setObjectName("MapaMetro")
        self.CalcularRuta = QtWidgets.QPushButton(self.centralwidget)
        self.CalcularRuta.setGeometry(QtCore.QRect(90, 170, 171, 31))
        self.CalcularRuta.setObjectName("CalcularRuta")
        self.comboDestino = QtWidgets.QComboBox(self.centralwidget)
        self.comboDestino.setGeometry(QtCore.QRect(90, 130, 171, 41))
        self.comboDestino.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboDestino.setObjectName("comboDestino")
        self.comboDestino.addItem("")
        self.comboDestino.setItemText(0, "")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.comboDestino.addItem("")
        self.MapaMetro.raise_()
        self.Destino.raise_()
        self.Origen.raise_()
        self.comboOrigen.raise_()
        self.Titulo.raise_()
        self.CalcularRuta.raise_()
        self.comboDestino.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Destino.setText(_translate("MainWindow", "Destino"))
        self.Origen.setText(_translate("MainWindow", "Origen"))
        self.comboOrigen.setItemText(1, _translate("MainWindow", "Tokyo"))
        self.comboOrigen.setItemText(2, _translate("MainWindow", "Kanda"))
        self.comboOrigen.setItemText(3, _translate("MainWindow", "Akihabara"))
        self.comboOrigen.setItemText(4, _translate("MainWindow", "Okachimachi"))
        self.comboOrigen.setItemText(5, _translate("MainWindow", "Ueno"))
        self.comboOrigen.setItemText(6, _translate("MainWindow", "Uguisudani"))
        self.comboOrigen.setItemText(7, _translate("MainWindow", "Nippori"))
        self.comboOrigen.setItemText(8, _translate("MainWindow", "Nishi-Nippori"))
        self.comboOrigen.setItemText(9, _translate("MainWindow", "Tabata"))
        self.comboOrigen.setItemText(10, _translate("MainWindow", "Komagome"))
        self.comboOrigen.setItemText(11, _translate("MainWindow", "Sugamo"))
        self.comboOrigen.setItemText(12, _translate("MainWindow", "Otsuka"))
        self.comboOrigen.setItemText(13, _translate("MainWindow", "Ikebukuro"))
        self.comboOrigen.setItemText(14, _translate("MainWindow", "Mejiro"))
        self.comboOrigen.setItemText(15, _translate("MainWindow", "Takadanobaba"))
        self.comboOrigen.setItemText(16, _translate("MainWindow", "Shin-Okubo"))
        self.comboOrigen.setItemText(17, _translate("MainWindow", "Shinjuku"))
        self.comboOrigen.setItemText(18, _translate("MainWindow", "Yoyogi"))
        self.comboOrigen.setItemText(19, _translate("MainWindow", "Harajuku"))
        self.comboOrigen.setItemText(20, _translate("MainWindow", "Shibuya"))
        self.comboOrigen.setItemText(21, _translate("MainWindow", "Ebisu"))
        self.comboOrigen.setItemText(22, _translate("MainWindow", "Meguro"))
        self.comboOrigen.setItemText(23, _translate("MainWindow", "Gotanda"))
        self.comboOrigen.setItemText(24, _translate("MainWindow", "Osaki"))
        self.comboOrigen.setItemText(25, _translate("MainWindow", "Shinagawa"))
        self.comboOrigen.setItemText(26, _translate("MainWindow", "Tamachi"))
        self.comboOrigen.setItemText(27, _translate("MainWindow", "Hamamatsucho"))
        self.comboOrigen.setItemText(28, _translate("MainWindow", "Shimbashi"))
        self.comboOrigen.setItemText(29, _translate("MainWindow", "Yurakucho"))
        self.comboOrigen.setItemText(30, _translate("MainWindow", "Sendagaya"))
        self.comboOrigen.setItemText(31, _translate("MainWindow", "Shinanomachi"))
        self.comboOrigen.setItemText(32, _translate("MainWindow", "Yotsuta"))
        self.comboOrigen.setItemText(33, _translate("MainWindow", "Iichigaya"))
        self.comboOrigen.setItemText(34, _translate("MainWindow", "Iidabashi"))
        self.comboOrigen.setItemText(35, _translate("MainWindow", "Suidobashi"))
        self.comboOrigen.setItemText(36, _translate("MainWindow", "Ochanomizu"))
        self.Titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">METRO TOKYO</span></p></body></html>"))
        self.CalcularRuta.setText(_translate("MainWindow", "CalcularRuta"))
        self.comboDestino.setItemText(1, _translate("MainWindow", "Tokyo"))
        self.comboDestino.setItemText(2, _translate("MainWindow", "Kanda"))
        self.comboDestino.setItemText(3, _translate("MainWindow", "Akihabara"))
        self.comboDestino.setItemText(4, _translate("MainWindow", "Okachimachi"))
        self.comboDestino.setItemText(5, _translate("MainWindow", "Ueno"))
        self.comboDestino.setItemText(6, _translate("MainWindow", "Uguisudani"))
        self.comboDestino.setItemText(7, _translate("MainWindow", "Nippori"))
        self.comboDestino.setItemText(8, _translate("MainWindow", "Nishi-Nippori"))
        self.comboDestino.setItemText(9, _translate("MainWindow", "Tabata"))
        self.comboDestino.setItemText(10, _translate("MainWindow", "Komagome"))
        self.comboDestino.setItemText(11, _translate("MainWindow", "Sugamo"))
        self.comboDestino.setItemText(12, _translate("MainWindow", "Otsuka"))
        self.comboDestino.setItemText(13, _translate("MainWindow", "Ikebukuro"))
        self.comboDestino.setItemText(14, _translate("MainWindow", "Mejiro"))
        self.comboDestino.setItemText(15, _translate("MainWindow", "Takadanobaba"))
        self.comboDestino.setItemText(16, _translate("MainWindow", "Shin-Okubo"))
        self.comboDestino.setItemText(17, _translate("MainWindow", "Shinjuku"))
        self.comboDestino.setItemText(18, _translate("MainWindow", "Yoyogi"))
        self.comboDestino.setItemText(19, _translate("MainWindow", "Harajuku"))
        self.comboDestino.setItemText(20, _translate("MainWindow", "Shibuya"))
        self.comboDestino.setItemText(21, _translate("MainWindow", "Ebisu"))
        self.comboDestino.setItemText(22, _translate("MainWindow", "Meguro"))
        self.comboDestino.setItemText(23, _translate("MainWindow", "Gotanda"))
        self.comboDestino.setItemText(24, _translate("MainWindow", "Osaki"))
        self.comboDestino.setItemText(25, _translate("MainWindow", "Shinagawa"))
        self.comboDestino.setItemText(26, _translate("MainWindow", "Tamachi"))
        self.comboDestino.setItemText(27, _translate("MainWindow", "Hamamatsucho"))
        self.comboDestino.setItemText(28, _translate("MainWindow", "Shimbashi"))
        self.comboDestino.setItemText(29, _translate("MainWindow", "Yurakucho"))
        self.comboDestino.setItemText(30, _translate("MainWindow", "Sendagaya"))
        self.comboDestino.setItemText(31, _translate("MainWindow", "Shinanomachi"))
        self.comboDestino.setItemText(32, _translate("MainWindow", "Yotsuta"))
        self.comboDestino.setItemText(33, _translate("MainWindow", "Iichigaya"))
        self.comboDestino.setItemText(34, _translate("MainWindow", "Iidabashi"))
        self.comboDestino.setItemText(35, _translate("MainWindow", "Suidobashi"))
        self.comboDestino.setItemText(36, _translate("MainWindow", "Ochanomizu"))


